version: 2
notify:
  webhooks:
    - url: https://coveralls.io/webhook?repo_token=$COVERALLS_REPO_TOKEN
jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache
      - run:
          name: install
          command: npm install
      - save_cache:
          key: dependency-cache
          paths:
            - ./node_modules
      - run:
          name: lint
          command: npm run lint:ci
      - run:
          name: test
          command: npm run cicoverage
      - run:
          name: codacy
          command: ./node_modules/.bin/codacy-coverage < ./coverage/lcov.info
      - run:
          name: code-climate
          command: ./node_modules/.bin/codeclimate-test-reporter < ./coverage/lcov.info
      - run:
          name: danger
          command: npm run danger
      - deploy:
          name: Maybe Deploy
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
              npm publish
            fi